### ISSUE TITLE
Unable to load images into SF2 web directory without manual hard copy or symlink

### ISSUE THREAD

**Issue by rrajkomar** [components/jqueryui#46]
There seems to be an issue (maybe a misuse on my part) with loading the images for themes from the components directory in SF2 application.
Loading the js ans css files is easy with Assetic but when loading the css files, the links to the related images are broken.

**Comment by drmonty** [comment]
I'm using symfony2, too, but your issue is not related to jqueryui, you're missing a setting for assetic. You should take a look in the docs about [cssrewrite](http://symfony.com/doc/current/cookbook/assetic/asset_management.html#including-css-stylesheets).

If you still have issues with assetic, feel free to ask your question on the [mailinglist of symfony](https://groups.google.com/forum/#!forum/symfony2).

**Comment by rrajkomar** [comment]
Hi,
Sorry but the link you provided gives samples on how to load either multiple css or multiple js files  (using the respective blocks) but only how to load one image at a time.
My issue is that the images cannot be accessed (I'm using cssrewrite) and it works fine for all images but the  jqueryui ones !
The issue may come from where the jqueryui packages copy the files (componenets directory) which is not taken into account by the cssrewrite ?

**Comment by drmonty** [comment]
@rrajkomar nothing is wrong with our css files, your issue is still assetic which do not reference the images correctly. Maybe it's possible to pass the correct path to assetic anyway...? I don't know and can't help you. You should ask your question on the mailinglist.

If you still think, there is something wrong with jquery-ui, you should post a bug report to the [developers of jquery-ui](http://bugs.jqueryui.com), we do only provide the shim repository.

**Comment by rrajkomar** [comment]
So far the only viable option I found was the one I copied in #47. 
But there's one downside : it breaks the standard architecture of a symfony project.
Ideally if when using your package, we could specify a path for each type of component that might help avoiding this.
